### Problem Statement

 It happens all the time: someone gives you data containing malformed strings,Python, lists and missing data. 
 How do you tidy it up so you can get on with the analysis?

 - Take this monstrosity as the DataFrame to use in the following puzzles:
 
 df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN','londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
                    'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                    'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                    'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                    '12. Air France', '"Swiss Air"']})

In [1]:
#Import the libraries
import numpy as np
import pandas as pd

In [17]:
#Create the dataframe using dict function
df =pd.DataFrame({'From_To':['LoNDon_paris', 'Madrid_miLAN', 'londON_StockhOlm', 'Budapest_PaRis', 'Brussels_londOn'],
                  'FlightNumber':[10045,np.nan,10065,np.nan,10085],
                  'RecentDelays':[[23,47],[],[24,43,87],[13],[67,32]],
                  'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', '12. Air France', '"Swiss Air"']})

In [18]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   From_To       5 non-null      object 
 1   FlightNumber  3 non-null      float64
 2   RecentDelays  5 non-null      object 
 3   Airline       5 non-null      object 
dtypes: float64(1), object(3)
memory usage: 288.0+ bytes


In [23]:
df.describe()

FlightNumber
count           3.0
mean        10065.0
std            20.0
min         10045.0
25%         10055.0
50%         10065.0
75%         10075.0
max         10085.0

In [24]:
df.corr()

FlightNumber
FlightNumber           1.0

In [25]:
df.dtypes

From_To          object
FlightNumber    float64
RecentDelays     object
Airline          object
dtype: object

1. Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column (instead of a float column).

In [26]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [27]:
df.iloc[:,1]

0    10045.0
1        NaN
2    10065.0
3        NaN
4    10085.0
Name: FlightNumber, dtype: float64

In [28]:
#To Check the null values  
np.isnan(df['FlightNumber'])

0    False
1     True
2    False
3     True
4    False
Name: FlightNumber, dtype: bool

In [29]:
#Drop the null values
df['FlightNumber'].dropna()

0    10045.0
2    10065.0
4    10085.0
Name: FlightNumber, dtype: float64

In [30]:
#To feed the corresponding particular values
df.loc[1]=10055

In [31]:
df.loc[3] = 10075 

In [32]:
#To Covert integer values
x = df['FlightNumber'].astype(int)

In [45]:
print(pd.DataFrame(x))

   FlightNumber
0         10045
1         10055
2         10065
3         10075
4         10085


2. The From_To column would be better as two separate columns! Split each
string on the underscore delimiter _ to give a new temporary DataFrame with
the correct values. Assign the correct column names to this temporary
DataFrame.

In [97]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [19]:
del df['FlightNumber']
del df['RecentDelays']
del df['Airline']

In [20]:
df

From_To
0      LoNDon_paris
1      Madrid_miLAN
2  londON_StockhOlm
3    Budapest_PaRis
4   Brussels_londOn

In [100]:
df.to_csv('sampledata')

In [119]:
import csv

fname ='sampledata'

with open(fname, 'r')as f:
    datareader =csv.reader(f,delimiter='_')
    header =next(datareader)
    print("Header:"+str(header))
    
    print("\n Content:")
    for line in datareader:
        words = line
        print(words)

Header:[',From', 'To']

 Content:
['0,LoNDon', 'paris']
['1,Madrid', 'miLAN']
['2,londON', 'StockhOlm']
['3,Budapest', 'PaRis']
['4,Brussels', 'londOn']


In [6]:
import csv

fname ='sampledata'

with open(fname, 'r')as f:
    data_reader =csv.reader(f, delimiter='_')
    header =next(data_reader)
    print("Header :"+str(header))
    
    print("\n Content:")
    for i in data_reader:
        print(i)

Header :[',From', 'To']

 Content:
['0,LoNDon', 'paris']
['1,Madrid', 'miLAN']
['2,londON', 'StockhOlm']
['3,Budapest', 'PaRis']
['4,Brussels', 'londOn']


3. Notice how the capitalisation of the city names is all mixed up in this
temporary DataFrame. Standardise the strings so that only the first letter is
uppercase (e.g. "londON" should become "London".)

In [32]:
df['From_To']

0        LoNDon_paris
1        Madrid_miLAN
2    londON_StockhOlm
3      Budapest_PaRis
4     Brussels_londOn
Name: From_To, dtype: object

In [22]:
data =df['From_To'].loc[2]

In [25]:
temp=data.capitalize()

In [26]:
temp

'London_stockholm'

In [9]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

5. In the RecentDelays column, the values have been entered into the
DataFrame as a list. We would like each first value in its own column, each
second value in its own column, and so on. If there isn't an Nth value, the value
should be NaN.
Expand the Series of lists into a DataFrame named delays, rename the columns
delay_1, delay_2, etc. and replace the unwanted RecentDelays column in df
with delays.

In [192]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [194]:
df.iloc[:,2]

0        [23, 47]
1              []
2    [24, 43, 87]
3            [13]
4        [67, 32]
Name: RecentDelays, dtype: object

In [224]:
df['Delays_1']=23
df['Delays_2']=47
df['Delays_3']=np.nan
df['Delays_4']=24
df['Delays_5']=43
df['Delays_6']=87
df['Delays_7']=13
df['Delays_8']=67
df['Delays_9']=32

In [225]:
df.reindex(columns=['From_To','FlightNumber','Delays_1','Delays_2','Delays_3','Delays_4','Delays_5','Delays_6','Delays_7','Delays_8','Delays_9','Airline'])

From_To  FlightNumber  Delays_1  Delays_2  Delays_3  Delays_4  \
0      LoNDon_paris       10045.0        23        47       NaN        24   
1      Madrid_miLAN           NaN        23        47       NaN        24   
2  londON_StockhOlm       10065.0        23        47       NaN        24   
3    Budapest_PaRis           NaN        23        47       NaN        24   
4   Brussels_londOn       10085.0        23        47       NaN        24   

   Delays_5  Delays_6  Delays_7  Delays_8  Delays_9              Airline  
0        43        87        13        67        32               KLM(!)  
1        43        87        13        67        32    <Air France> (12)  
2        43        87        13        67        32  (British Airways. )  
3        43        87        13        67        32       12. Air France  
4        43        87        13        67        32          "Swiss Air"

In [171]:
df

From_To  FlightNumber  RecentDelays              Airline   Delays
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)  Missing
1      Madrid_miLAN           NaN            []    <Air France> (12)  Missing
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )  Missing
3    Budapest_PaRis           NaN          [13]       12. Air France  Missing
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"  Missing